### ISSUE TITLE
how to set the carmera params?

### ISSUE THREAD

**Issue by WuMianzhi** [inealey/points2pano#1]
Hello, I am using your code to convert a las file to a 360 pic, if I think the way u generate 360 pic is take a pic, how do i set the carmera's pos, or generate 360 pic in different place?

**Comment by inealey** [comment]
Hi!
The algorithm works by "splatting" the (3D) points measured by a LiDAR scanner onto a 2D canvas. 
I chose an equirectangular projection because makes the math simple.

look up "how to convert cartesian to polar coordinates" and take a look at lines 130 and 133. You will see that we are computing theta and phi values based on a viewer location of (0,0,0) - essentially we wanted a POV as if you are standing where the LiDAR scanner was. 

If you wanted to move the perspective away from the origin, you can add an offset to the values stored in `las.x`, `las.y`, and `las.z` when computing the polar coordinates.

**Comment by WuMianzhi** [comment]
> Hi! The algorithm works by "splatting" the (3D) points measured by a LiDAR scanner onto a 2D canvas. I chose an equirectangular projection because makes the math simple.
> 
> look up "how to convert cartesian to polar coordinates" and take a look at lines 130 and 133. You will see that we are computing theta and phi values based on a viewer location of (0,0,0) - essentially we wanted a POV as if you are standing where the LiDAR scanner was.
> 
> If you wanted to move the perspective away from the origin, you can add an offset to the values stored in `las.x`, `las.y`, and `las.z` when computing the polar coordinates.

i got it, thanks for you reply~
